name: workflow-manager
home: https://github.com/teamhephy/workflow-manager
version: 2.6.3
description: "Deis Workflow Manager: Cluster First Aid"
maintainers:
  - name: Deis Team
    email: engineering@deis.com
